### PR TITLE
Compressed 811 .png assets

### PR DESCRIPTION
**Pull request by nivomi**
Assets were run through PNGOUT, OptiPNG, DeflOpt, and Zopflipng. 

811 files were changed, other assets were attempted but could not be further compressed. Total main/app/src/assets filesize changed from 9,870,008 bytes to 9,157,483 bytes _(717.5 kB reduction!)_

### CODE REVIEW

**Comment by JosephMichels** [comment]
Thanks for doing this. Most of the old ones had been run through optimizes, but the newly created ones had not.

Do you know if all the optimizers used are lossless?

**Comment by nivomi** [comment]
All optimizers used are lossless - **except** for some metadata, potentially, and **fully transparent pixels with color data** - if the alpha channel is zero, but the other channels have (useless, generally) color data, the optimizers will zero out the color data.

This generally doesn't matter, unless you're doing something unique and strange.

**Comment by nivomi** [comment]
Yo, just wondering if you need any changes to the methodology of compression for this request - I can run the images again with (generally useless) transparent pixels retained, if you'd like

**Comment by JosephMichels** [comment]
No, we were going to add a couple more images for a few things that we are missing and then run the optimizations on all of them at once, but I'll go ahead and accept this now, no real reason to wait. Thanks for doing this, I'm not sure what the effect will be on the install/apk size, but I suppose any bit helps.

**Pull request merged**
