### PR TITLE
Updated gradle and build tools

### PR DESCRIPTION
**Pull request by CanOrhan**
Hey - I'd like to do a little work on this but thought that I'd first do some housekeeping and update the gradle & build tools versions we're using.

### CODE REVIEW

**Comment by kamegami13** [comment]
Thanks. If you're wanting to contribute I can add you to our Slack chat room. Just post an email for invite.

**Comment by CanOrhan** [comment]
Yup :) I noticed you had one so I've sent an email already.

**Comment by kamegami13** [comment]
Where did you send an email?

**Comment by jaysondc** [comment]
He sent it to me and I forwarded him an invite. Looking forward to having your help!

**Pull request merged**
